name: Development

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_dispatch:
  workflow_call:

jobs:
  BuildTest:
    name: Build Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: "â˜ï¸ checkout repository"
        uses: actions/checkout@v2

      - name: "ğŸ”§ Install linux dependencies"
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install build-essential libtool autoconf unzip wget openssl -y
          version=3.27
          build=7
          mkdir ~/temp
          cd ~/temp
          wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
          tar -xzvf cmake-$version.$build.tar.gz
          cd cmake-$version.$build/
          ./bootstrap
          make -j$(nproc)
          sudo make install

      - name: "ğŸ”§ Install Windows dependencies"
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake

      - name: "ğŸ—ï¸ Make"
        run: make

  RunTests:
    name: Run Tests
    needs: BuildTest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: "â˜ï¸ checkout repository"
        uses: actions/checkout@v2

      - name: "ğŸ”§ Install Linux dependencies"
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install cmake -y

      - name: "ğŸ”§ Install Windows dependencies"
        if: matrix.os == 'windows-latest'
        run: |
          choco install make
          choco install cmake

      - name: "ğŸ—ï¸ Make"
        run: make

      - name: "ğŸ§ª Run Tests"
        run: echo "Tests not implemented yet"