name: Development

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_dispatch:
  workflow_call:

jobs:
  macBuildTest:
    name: MacOs Build test
    runs-on: macos-latest
    steps:
      - name: "â˜ï¸ checkout repository"
        uses: actions/checkout@v2

      - name: "ğŸ—ï¸ Make"
        run: make

  linuxBuildTest:
    name: Linux Build test
    runs-on: ubuntu-latest
    steps:
      - name: "â˜ï¸ checkout repository"
        uses: actions/checkout@v2

      - name: "ğŸ”§ Install dependencies"
        run: |
          sudo apt update
          sudo apt install cmake -y
  
      - name: "ğŸ—ï¸ Make"
        run: make

  windowsBuildTest:
    name: Windows Build test
    runs-on: windows-latest
    steps:
      - name: "â˜ï¸ checkout repository"
        uses: actions/checkout@v2

      - name: "ğŸ”§ Install dependencies"
        run: |
          choco install make
          choco install cmake

      - name: "ğŸ—ï¸ Make"
        run: make